# Generated by Django 3.1.5 on 2021-01-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Модель телефона')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('image', models.URLField(blank=True, verbose_name='Изображение')),
                ('release_date', models.DateField(blank=True, verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'телефон',
                'verbose_name_plural': 'Телефон',
            },
        ),
    ]
